---
- name: packages 
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  # vars:
  #   - my_pkgs:
  #     - sublime-text
  #     - google-chrome-stable

  tasks:
  - name: Install GPG key for SubLimeText
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: Add specified repositories into sources list using specified filename
    apt_repository:
      repo: deb {{ item.repo }} {{ item.add }}
      state: present
      filename: "{{ item.file }}"
    with_items:
      - repo: https://download.sublimetext.com/
        add: apt/stable/
        file: sublime
      - repo: '[arch=amd64] http://dl.google.com/linux/chrome/deb/'
        add: stable main
        file: google-chrome

  - name: Install packages
    apt:
      state: installed
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ my_pkgs }}"

  # - name: python2.7
  #   apt: name=python2.7 state=present

  - name: install pip
    apt: name=python3-pip state=present

  - name: install wget
    apt: name=wget state=latest

  - name: wget
    command: wget https://az764295.vo.msecnd.net/stable/f46c4c469d6e6d8c46f268d1553c5dc4b475840f/code_1.27.2-1536736588_amd64.deb

  - name: libgconf
    apt: name=libgconf-2-4 state=latest

  - name: install visual studio code
    command: dpkg -i code_1.27.2-1536736588_amd64.deb

  # - name: install ssh
  #   apt: name=openssh-server state=latest

  - name: ssh key generate
    command: ssh-keygen


